import { cashOut, dayGoals, referrals, reviews, snapshot, surveys } from "@/lib/snapshot";
import type { Lead } from "@/lib/crm-data";
import type { Resource } from "@/features/book/roster";
import { familyOf, isWatch, type BookEvent } from "@/features/book/types";
import { hourOf } from "@/features/book/time";
import { STEEL, WASH, MID, LIVE, pack, valueOf, prep_buildToday2, type Mark, type Rank, type FlowBar, type FieldNow } from "./part-01";

export function step_03(ctx: any): any {
return { __halt: true as const, __ret: {
    sold: ctx.sold,
    soldN: ctx.soldN,
    ticket: ctx.ticket,
    members: snapshot.membersToday,
    memberSold: snapshot.memberSoldToday,
    yesterday: ctx.yesterday,
    closeRate: ctx.closeRate,
    decided: ctx.decided,
    passed: ctx.passed.length,
    left: ctx.left.length,
    ran: ctx.passed.length,
    closed: ctx.soldN,
    onBook: ctx.left.reduce((s: any, e: any) => s + valueOf(e, ctx.leads), 0),
    cashIn: ctx.cashIn,
    spent: ctx.spent,
    expected: ctx.expected,
    cashOut,
    marketingSpend: ctx.marketingSpend,
    marketingSold: ctx.marketingSold,
    mktBySource: ctx.mktBySource,
    mktSpark: ctx.mktSpark,
    dealSpark: ctx.dealSpark,
    actionCats: ctx.actionCats,
    payroll: ctx.payroll,
    payrollYest: snapshot.payrollYesterday,
    jobsDone: ctx.jobsDone,
    jobsOut: ctx.jobSplit[1].n,
    jobsPending: ctx.jobsPending,
    tixOpen: ctx.tixOpen,
    tixAdded: ctx.tixAdded,
    tixClosed: ctx.tixClosed,
    reviews,
    reviewScore: snapshot.reviewScore,
    reviewCount: snapshot.reviewCount,
    referrals,
    surveys,
    flow: ctx.flow,
    mix: ctx.mix,
    appt: ctx.appt,
    runSplit: ctx.runSplit,
    jobSplit: ctx.jobSplit,
    tix: ctx.tix,
    leadSplit: ctx.leadSplit,
    leadsIn: snapshot.leadsToday,
    hour: ctx.hour,
    behindN: ctx.behindN,
    marks: ctx.marks,
    trends: ctx.trends,
    unsigned: ctx.prod.filter((e: any) => isWatch(e)).length,
    top: [...ctx.c.top, ...ctx.k.top, ...ctx.s.top],
    bottom: [...ctx.c.bottom, ...ctx.k.bottom, ...ctx.s.bottom],
    nosit: ctx.nosit.length,
    field: ctx.field,
  } }
}
