import { accounts, leads, projects } from "@/lib/crm-data";
import {
  cashLoan,
  defaultChecks,
  defaultPacket,
  defaultPost,
  defaultPre,
  emptyPermit,
  emptyRebate,
  emptyTest,
  type JobFile,
  type Stage,
} from "./types";

const atticBefore = "/brand/slides/house.jpg";

export function seedJobs(): JobFile[] {
  const cho: JobFile = {
    jobId: "P-331",
    personId: "L-4788",
    leadId: "L-4788",
    accountId: "A-204",
    name: "Cho — attic + HVAC",
    product: "Attic + HVAC",
    pm: "Tasha Reed",
    closer: "Dana Ortiz",
    stage: "Scheduled",
    holds: [],
    sold: 31250,
    labor: 4200,
    commission: 3125,
    extras: 0,
    crew: "Crew 2 — Tasha",
    truck: "Truck 4",
    window: "Sep 22 · 7a–3p",
    assignments: [
      { id: "CA-1", crew: "Crew 2 — Tasha", truck: "Truck 4", day: "2026-09-22", start: "07:00", end: "15:00", scopes: ["SC-1", "SC-3"], kind: "internal", company: "", woId: "WO-14" },
      { id: "CA-2", crew: "Crew 1 — Evan", truck: "Truck 2", day: "2026-09-22", start: "08:00", end: "16:00", scopes: ["SC-2"], kind: "internal", company: "" },
    ],
    soldNotes: "Both home. Hatch in the hall. Dumpster off the street for HOA.",
    scope: [
      {
        id: "SC-1",
        label: "Attic R-49",
        kind: "product",
        categoryId: "attic",
        amount: 8900,
        qty: 1850,
        notes: "Blow R-49. Baffles at the eaves. Hatch weatherstrip.",
        quotedCost: 2100,
        estHours: 6,
        media: [{ id: "M-1", cat: "Before", name: "Hatch", url: atticBefore, kind: "photo" }],
        owner: "",
        promiseDone: false,
        bom: [
          { id: "B-1", name: "Cellulose bag", estQty: 42, usedQty: 0, unit: "bag", unitCost: 14, supplier: "Cameron Ashley", ordered: true },
          { id: "B-2", name: "Baffle", estQty: 24, usedQty: 0, unit: "ea", unitCost: 3.2, supplier: "Cameron Ashley", ordered: true },
        ],
      },
      {
        id: "SC-2",
        label: "HVAC replacement",
        kind: "product",
        categoryId: "hvac",
        amount: 18600,
        qty: 1,
        notes: "4-ton split. Goodman. Old pad is cracked — new pad in adders.",
        quotedCost: 9800,
        estHours: 8,
        media: [],
        owner: "",
        promiseDone: false,
        bom: [
          { id: "B-3", name: "4-ton condenser", estQty: 1, usedQty: 0, unit: "ea", unitCost: 6200, supplier: "WinSupply", ordered: true },
          { id: "B-4", name: "Coil", estQty: 1, usedQty: 0, unit: "ea", unitCost: 2100, supplier: "WinSupply", ordered: true },
        ],
      },
      {
        id: "SC-3",
        label: "Ducts",
        kind: "product",
        categoryId: "ducts",
        amount: 3750,
        qty: 1,
        notes: "Replace the supply trunk in the garage. Seal boots.",
        quotedCost: 900,
        estHours: 4,
        media: [],
        owner: "",
        promiseDone: false,
        plan: { status: "Released", approvedBy: "Office" },
        bom: [
          { id: "B-5", name: '8" trunk 10\'', estQty: 4, usedQty: 0, unit: "ea", unitCost: 38, supplier: "WinSupply", ordered: false },
          { id: "B-6", name: "Boot", estQty: 10, usedQty: 0, unit: "ea", unitCost: 9, supplier: "WinSupply", ordered: false },
        ],
      },
      {
        id: "SC-4",
        label: "New pad",
        kind: "adder",
        categoryId: "hvac",
        amount: 350,
        qty: 1,
        notes: "Old pad cracked.",
        quotedCost: 85,
        estHours: 0.5,
        media: [],
        owner: "",
        promiseDone: false,
        bom: [{ id: "B-7", name: "Pad", estQty: 1, usedQty: 0, unit: "ea", unitCost: 85, supplier: "WinSupply", ordered: false }],
      },
      {
        id: "SC-5",
        label: "Dumpster off the street",
        kind: "promise",
        categoryId: "attic",
        amount: 0,
        qty: 1,
        notes: "HOA. Office calls dump.",
        quotedCost: 0,
        estHours: 0,
        media: [],
        owner: "Priya Shah",
        promiseDone: false,
        bom: [],
      },
    ],
    warranty: true,
    loan: {
      vendor: "GoodLeap",
      amount: 31250,
      dealerFee: 2188,
      term: 144,
      rate: 7.99,
      status: "NTP",
      notes: "Stip: proof of insurance. Alyssa is the borrower.",
      fundedAmount: 0,
    },
    workOrders: [
      {
        id: "WO-14",
        assignId: "CA-1",
        status: "Sent",
        day: "2026-09-22",
        crew: "Crew 2 — Tasha",
        notes: "Attic R-49 + ducts.",
        file: { name: "WO-14.pdf", url: "#" },
      },
    ],
    pos: [
      { id: "PO-88", vendor: "Carrier", amount: 9800, status: "Sent", what: "4-ton condenser + coil", scopeId: "SC-2", file: { name: "PO-88-Carrier.pdf", url: "#" } },
      { id: "PO-81", vendor: "GreenFiber", amount: 2100, status: "Received", what: "Cellulose", scopeId: "SC-1", file: { name: "PO-81-GreenFiber.pdf", url: "#" } },
    ],
    changeOrders: [],
    invoices: [
      {
        id: "INV-41",
        kind: "Deposit",
        amount: 5000,
        paid: 0,
        status: "Sent",
        file: { name: "INV-41.pdf", url: "#" },
        payments: [],
      },
    ],
    events: [
      { id: "EV-1", scopeId: "SC-1", process: "Attic blow", day: "2026-09-22", start: "07:00", end: "15:00", crew: "Crew 2 — Tasha", assignId: "CA-1", status: "Set" },
      { id: "EV-2", scopeId: "SC-3", process: "Ducts", day: "2026-09-22", start: "07:00", end: "15:00", crew: "Crew 2 — Tasha", assignId: "CA-1", status: "Set" },
    ],
    punch: [{ id: "PU-1", item: "Seal hatch weatherstrip", owner: "Crew 2", status: "Open" }],
    equipment: [
      { id: "EQ-1", name: "4-ton condenser", model: "24ACC636A003", serial: "", ahri: "207398123", eta: "Sep 19", status: "Ordered", oldRecovered: false, scopeId: "SC-2" },
      { id: "EQ-2", name: "Coil", model: "CAPFA1818C6", serial: "", ahri: "", eta: "Sep 19", status: "Ordered", oldRecovered: false, scopeId: "SC-2" },
    ],
    checks: defaultChecks().map((c) => (c.id === "equip" ? { ...c, on: true } : c)),
    punches: [{ id: "HR-1", who: "Tasha Reed", day: "Sep 12", scopeId: "SC-1", leftYard: "06:40", onSite: "07:10", complete: "09:00", back: "09:25" }],
    access: "Side gate. Dogs in. HOA needs dumpster off the street.",
    permit: { number: "MECH-4491", city: "Scottsdale", inspection: "2026-09-24", result: "Scheduled", file: { name: "permit-MECH-4491.pdf", url: "#" } },
    rebate: { utility: "SRP", program: "Home Performance", amount: 800, status: "Reserved", reservation: "SRP-8821", file: undefined },
    testOut: emptyTest(),
    preCheck: { ...defaultPre(), items: defaultPre().items.map((i) => ({ ...i, on: true })), signedBy: "Alyssa Cho", signedAt: "Sep 8" },
    postCheck: defaultPost(),
    packet: defaultPacket(),
    installRev: 1,
    financeRev: 1,
  };
  const rest = projects
    .filter((p) => p.id !== "P-331")
    .map((p) => {
      const account = accounts.find((a) => a.id === p.accountId);
      const lead = leads.find((l) => l.name === account?.name);
      const contact = lead?.id ?? p.accountId;
      const sid = `SC-${p.id}`;
      return {
        jobId: p.id,
        personId: contact,
        leadId: lead?.id ?? "",
        accountId: p.accountId,
        name: p.name,
        product: p.product,
        pm: p.pm,
        closer: "Dana Ortiz",
        stage: (p.status === "On hold" ? "Sold" : p.status) as Stage,
        holds: p.status === "On hold" ? [{ kind: "HOA" as const, note: "Waiting on HOA. Need the written sign-off.", at: "Sep 10" }] : [],
        sold: p.amount,
        labor: Math.round(p.amount * 0.12),
        commission: Math.round(p.amount * 0.1),
        extras: 0,
        crew: p.pm,
        truck: "Truck 2",
        window: p.install,
        assignments: p.install
          ? [{ id: `CA-${p.id}`, crew: p.pm, truck: "Truck 2", day: "", start: "07:00", end: "15:00", scopes: [sid], kind: "internal" as const, company: "" }]
          : [],
        soldNotes: "",
        scope: [{ id: sid, label: p.product, kind: "product" as const, categoryId: p.product.toLowerCase().includes("hvac") ? "hvac" : p.product.toLowerCase().includes("duct") || p.product.toLowerCase().includes("aero") ? "ducts" : "attic", amount: p.amount, qty: 1, notes: "", quotedCost: Math.round(p.amount * 0.4), estHours: 8, media: [], owner: "", promiseDone: false, bom: [] }],
        warranty: p.product.toLowerCase().includes("attic"),
        loan: { ...cashLoan(), amount: p.amount },
        workOrders: [],
        pos: [],
        changeOrders: [],
        invoices:
          p.status === "Closed"
            ? [{ id: `INV-${p.id.slice(2)}`, kind: "Final" as const, amount: p.amount, paid: p.amount, status: "Paid" as const, payments: [{ id: `PY-${p.id}`, amount: p.amount, at: p.install, how: "Cash", status: "Paid" as const }] }]
            : [],
        events: p.install ? [{ id: `EV-${p.id}`, scopeId: sid, process: p.product, day: p.install, start: "07:00", end: "15:00", crew: p.pm, status: "Set" as const }] : [],
        punch: [],
        equipment: [],
        checks: defaultChecks(),
        punches: [],
        access: "",
        permit: emptyPermit(),
        rebate: emptyRebate(),
        testOut: emptyTest(),
        preCheck: defaultPre(),
        postCheck: defaultPost(),
        packet: defaultPacket(),
        installRev: 1,
        financeRev: 1,
      };
    });
  return [cho, ...rest];
}
