import { LIVE, MID, STEEL, WASH, pack } from "./palette";
import type { SalesBoard } from "./types";

export const wtd: SalesBoard = {
    id: "wtd",
    vs: "last week this time",
    sold: 186420,
    priorSold: 164800,
    goalSold: 260000,
    deals: 11,
    priorDeals: 10,
    goalDeals: 16,
    close: 42,
    priorClose: 38,
    goalClose: 40,
    avg: 16947,
    priorAvg: 16480,
    cancel: 9800,
    priorCancel: 12400,
    cashIn: 84200,
    priorCash: 76800,
    finance: 61200,
    card: 23000,
    leads: 47,
    priorLeads: 41,
    appts: 24,
    priorAppts: 21,
    runs: 18,
    priorRuns: 16,
    cancelledN: 1,
    jobs: 6,
    priorJobs: 5,
    opps: 14,
    mix: pack([
      { label: "Set", n: 5, tone: WASH },
      { label: "Ran", n: 7, tone: STEEL },
      { label: "Sold", n: 11, tone: LIVE },
      { label: "Cancelled", n: 1, tone: WASH, mark: "stop" },
    ]),
    leadSplit: pack([
      { label: "Called", n: 36, tone: STEEL },
      { label: "Not called", n: 11, tone: MID, mark: "watch" },
    ]),
    apptSplit: pack([
      { label: "Ran", n: 18, tone: STEEL },
      { label: "Still set", n: 6, tone: MID },
    ]),
    jobSplit: pack([
      { label: "Closed", n: 3, tone: MID },
      { label: "Active", n: 2, tone: STEEL },
      { label: "Hold", n: 1, tone: WASH, mark: "watch" },
    ]),
    products: [
      { name: "Attic insulation", amount: 62400 },
      { name: "HVAC replacement", amount: 48600 },
      { name: "Air sealing", amount: 28600 },
      { name: "Duct sealing", amount: 21400 },
      { name: "Insulation removal", amount: 14200 },
      { name: "Windows", amount: 11220 },
    ],
    offices: [
      { name: "Phoenix", amount: 68400 },
      { name: "Scottsdale", amount: 54200 },
      { name: "Dallas", amount: 36200 },
      { name: "Fort Worth", amount: 18600 },
      { name: "North Phoenix", amount: 9020 },
    ],
    funnel: [
      { label: "Leads", n: 47, rate: "100%" },
      { label: "Appts", n: 24, rate: "51%" },
      { label: "Runs", n: 18, rate: "75%" },
      { label: "Sold", n: 11, rate: "61%" },
      { label: "Jobs", n: 6, rate: "55%" },
    ],
    bars: [
      { label: "Sun", now: 18400, prior: 12200 },
      { label: "Mon", now: 40150, prior: 50920 },
      { label: "Tue", now: 48600, prior: 36200 },
      { label: "Wed", now: 42800, prior: 28600 },
      { label: "Thu", now: 36470, prior: 36880, hot: true },
      { label: "Fri", now: 0, prior: 0 },
      { label: "Sat", now: 0, prior: 0 },
    ],
    barTitle: "Sold this week",
    barHint: "Steel is this week. Gray is last week this day.",
    closers: [
      { name: "Dana Ortiz", why: "4 sold", amount: 86420, count: 4 },
      { name: "Marco Velez", why: "3 sold", amount: 61200, count: 3 },
      { name: "Luis Haddad", why: "2 sold", amount: 33180, count: 2 },
      { name: "Cole Brennan", why: "2 sold", amount: 5620, count: 2 },
      { name: "Nate Solis", why: "0 sold", amount: 0, count: 0 },
    ],
    setters: [
      { name: "Priya Shah", why: "18 set · 11 ran", amount: 18, count: 11 },
      { name: "Amber Quinn", why: "14 set · 9 ran", amount: 14, count: 9 },
    ],
    unmarked: 2,
    nosit: 1,
    missed: 1,
    oneleg: 0,
  };
