import { LIVE, MID, STEEL, WASH, pack } from "./palette";
import type { SalesBoard } from "./types";

export const day: SalesBoard = {
    id: "day",
    vs: "yesterday this hour",
    sold: 40150,
    priorSold: 50920,
    goalSold: 52000,
    deals: 2,
    priorDeals: 3,
    goalDeals: 3,
    close: 40,
    priorClose: 50,
    goalClose: 40,
    avg: 20075,
    priorAvg: 16973,
    cancel: 0,
    priorCancel: 9800,
    cashIn: 18640,
    priorCash: 16220,
    finance: 28640,
    card: 0,
    leads: 6,
    priorLeads: 5,
    appts: 9,
    priorAppts: 8,
    runs: 5,
    priorRuns: 6,
    cancelledN: 0,
    jobs: 2,
    priorJobs: 3,
    opps: 4,
    sitsLeft: 4,
    mix: pack([
      { label: "Set", n: 4, tone: WASH },
      { label: "Ran", n: 3, tone: STEEL },
      { label: "Sold", n: 2, tone: MID },
      { label: "Cancelled", n: 0, tone: WASH },
    ]),
    leadSplit: pack([
      { label: "Called", n: 4, tone: STEEL },
      { label: "Not called", n: 2, tone: MID, mark: "watch" },
    ]),
    apptSplit: pack([
      { label: "Ran", n: 5, tone: STEEL },
      { label: "Left", n: 4, tone: MID },
    ]),
    jobSplit: pack([
      { label: "Closed", n: 0, tone: MID },
      { label: "Out", n: 2, tone: STEEL },
      { label: "Pending", n: 0, tone: WASH },
    ]),
    products: [
      { name: "HVAC 4-ton + ducts", amount: 28640 },
      { name: "Attic R-49", amount: 11510 },
    ],
    offices: [
      { name: "Scottsdale", amount: 28640 },
      { name: "Phoenix", amount: 11510 },
    ],
    funnel: [
      { label: "Leads", n: 6, rate: "100%" },
      { label: "Appts", n: 9, rate: "—" },
      { label: "Runs", n: 5, rate: "56%" },
      { label: "Sold", n: 2, rate: "40%" },
      { label: "Jobs", n: 2, rate: "100%" },
    ],
    bars: [
      { label: "6a", now: 0, prior: 0 },
      { label: "7a", now: 0, prior: 1 },
      { label: "8a", now: 1, prior: 2 },
      { label: "9a", now: 0, prior: 1 },
      { label: "10a", now: 1, prior: 0 },
      { label: "11a", now: 1, prior: 1 },
      { label: "12p", now: 1, prior: 1 },
      { label: "1p", now: 1, prior: 1 },
      { label: "2p", now: 0, prior: 0 },
      { label: "3p", now: 0, prior: 0 },
      { label: "4p", now: 2, prior: 1 },
      { label: "5p", now: 2, prior: 2 },
      { label: "6p", now: 3, prior: 1, hot: true },
      { label: "7p", now: 1, prior: 1 },
      { label: "8p", now: 0, prior: 0 },
      { label: "9p", now: 0, prior: 0 },
    ],
    barTitle: "Runs by hour",
    barHint: "Steel is today. Gray is yesterday. Navy is now (6p).",
    closers: [
      { name: "Dana Ortiz", why: "Hale HVAC. Out at 5p", amount: 28640, count: 1 },
      { name: "Marco Velez", why: "Cho attic. Out at 7p", amount: 11510, count: 1 },
      { name: "Luis Haddad", why: "Patel no run 4p", amount: 0, count: 0 },
      { name: "Cole Brennan", why: "Briggs 6:30p still out", amount: 0, count: 0 },
      { name: "Nate Solis", why: "Not on the book", amount: 0, count: 0 },
    ],
    setters: [
      { name: "Priya Shah", why: "3 set today", amount: 3, count: 2 },
      { name: "Amber Quinn", why: "2 set today", amount: 2, count: 1 },
    ],
    unmarked: 2,
    nosit: 1,
    missed: 0,
    oneleg: 0,
  };
