import { LIVE, MID, STEEL, WASH, pack } from "./palette";
import type { SalesBoard } from "./types";

export const mtd: SalesBoard = {
    id: "mtd",
    vs: "last month this time",
    sold: 257220,
    priorSold: 442000,
    goalSold: 480000,
    deals: 18,
    priorDeals: 31,
    goalDeals: 32,
    close: 39,
    priorClose: 37,
    goalClose: 40,
    avg: 14290,
    priorAvg: 14258,
    cancel: 18600,
    priorCancel: 12400,
    cashIn: 186400,
    priorCash: 312800,
    finance: 142000,
    card: 44400,
    leads: 128,
    priorLeads: 186,
    appts: 64,
    priorAppts: 92,
    runs: 46,
    priorRuns: 68,
    cancelledN: 4,
    jobs: 14,
    priorJobs: 22,
    opps: 38,
    mix: pack([
      { label: "Set", n: 14, tone: WASH },
      { label: "Ran", n: 28, tone: STEEL },
      { label: "Sold", n: 18, tone: MID },
      { label: "Cancelled", n: 4, tone: WASH, mark: "stop" },
    ]),
    leadSplit: pack([
      { label: "Called", n: 104, tone: STEEL },
      { label: "Not called", n: 24, tone: MID, mark: "watch" },
    ]),
    apptSplit: pack([
      { label: "Ran", n: 46, tone: STEEL },
      { label: "Still set", n: 18, tone: MID },
    ]),
    jobSplit: pack([
      { label: "Closed", n: 8, tone: MID },
      { label: "Active", n: 5, tone: STEEL },
      { label: "Hold", n: 1, tone: WASH, mark: "watch" },
    ]),
    products: [
      { name: "Attic insulation", amount: 84200 },
      { name: "HVAC replacement", amount: 61200 },
      { name: "Air sealing", amount: 42800 },
      { name: "Duct sealing", amount: 28600 },
      { name: "Insulation removal", amount: 18400 },
      { name: "Windows", amount: 22020 },
    ],
    offices: [
      { name: "Phoenix", amount: 98400 },
      { name: "Scottsdale", amount: 74200 },
      { name: "Dallas", amount: 48600 },
      { name: "Fort Worth", amount: 24800 },
      { name: "North Phoenix", amount: 11220 },
    ],
    funnel: [
      { label: "Leads", n: 128, rate: "100%" },
      { label: "Appts", n: 64, rate: "50%" },
      { label: "Runs", n: 46, rate: "72%" },
      { label: "Sold", n: 18, rate: "39%" },
      { label: "Jobs", n: 14, rate: "78%" },
    ],
    bars: [
      { label: "W1", now: 86400, prior: 112000 },
      { label: "W2", now: 98200, prior: 128400 },
      { label: "W3", now: 72620, prior: 201600, hot: true },
    ],
    barTitle: "Sold this month",
    barHint: "Steel is this month. Gray is last month this week.",
    closers: [
      { name: "Dana Ortiz", why: "6 sold", amount: 86420, count: 6 },
      { name: "Marco Velez", why: "4 sold", amount: 61200, count: 4 },
      { name: "Luis Haddad", why: "3 sold", amount: 42800, count: 3 },
      { name: "Cole Brennan", why: "3 sold", amount: 38600, count: 3 },
      { name: "Nate Solis", why: "2 sold", amount: 28200, count: 2 },
    ],
    setters: [
      { name: "Priya Shah", why: "28 set · 18 ran", amount: 28, count: 18 },
      { name: "Amber Quinn", why: "22 set · 16 ran", amount: 22, count: 16 },
      { name: "Office inbound", why: "14 set · 12 ran", amount: 14, count: 12 },
    ],
    unmarked: 6,
    nosit: 3,
    missed: 2,
    oneleg: 1,
  };
