export const __rows1 = [
{
    id: "M-6",
    personId: "L-4821",
    channel: "internal",
    from: "shop",
    at: "Sep 12 8:20a",
    text: "Both spouses required. Do not run if only one is home.",
    reactions: [{ emoji: "👍", by: "Marco Velez" }, { emoji: "✅", by: "Priya Shah" }],
  },
{
    id: "M-7",
    personId: "L-4821",
    channel: "note",
    from: "shop",
    at: "Sep 11 4:05p",
    text: "Both spouses need to be home. Dog in backyard.",
  },
{
    id: "M-8",
    personId: "L-4821",
    channel: "internal",
    from: "shop",
    at: "Sep 14 9:12a",
    text: "HOA wants tan, not white.",
    nest: { kind: "ticket", id: "T-91", title: "HOA baffle color" },
    actionId: "T-91",
    actionKind: "ticket",
    reactions: [{ emoji: "👍", by: "Marco Velez" }],
  },
{
    id: "M-9",
    personId: "L-4821",
    channel: "internal",
    from: "shop",
    at: "Sep 14 9:40a",
    text: "Got it. Sending the swatch.",
    nest: { kind: "ticket", id: "T-91", title: "HOA baffle color" },
    actionId: "T-91",
    actionKind: "ticket",
    replyTo: "M-8",
  },
{
    id: "M-91a",
    personId: "L-4821",
    channel: "sms",
    from: "shop",
    at: "Sep 14 9:05a",
    text: "Elena, HOA wants the baffle to match the vents. Can you shoot the approved color from the letter?",
    actionId: "T-91",
    actionKind: "ticket",
  },
{
    id: "M-91b",
    personId: "L-4821",
    channel: "sms",
    from: "customer",
    at: "Sep 14 9:22a",
    text: "Tan on the letter. I'll text a photo when I'm home.",
    actionId: "T-91",
    actionKind: "ticket",
  },
{
    id: "M-91c",
    personId: "L-4821",
    channel: "sms",
    from: "shop",
    at: "Sep 14 9:28a",
    text: "Got it. Priya will send the swatch to the board.",
    actionId: "T-91",
    actionKind: "ticket",
  },
{
    id: "M-91k",
    personId: "L-4821",
    channel: "internal",
    from: "shop",
    at: "Sep 14 10:02a",
    text: "Need the hatch photo before we order.",
    nest: { kind: "task", id: "K-1", title: "Photo of approved baffle" },
    actionId: "K-1",
    actionKind: "task",
  },
];
