export const SHOP_BY: Record<string, string> = {
  "M-1": "Priya Shah",
  "M-1c": "Priya Shah",
  "M-3": "Priya Shah",
  "M-3e": "Priya Shah",
  "M-3ef": "Priya Shah",
  "M-4": "Dana Ortiz",
  "M-5": "Tasha Reed",
  "M-6": "Priya Shah",
  "M-7": "Priya Shah",
  "M-8": "Wrex Lindsay",
  "M-9": "Marco Velez",
  "M-91a": "Priya Shah",
  "M-91c": "Tasha Reed",
  "M-91k": "Marco Velez",
  "M-91r": "Amber Quinn",
};

export const __rows0 = [
{
    id: "M-1",
    personId: "L-4821",
    channel: "sms",
    from: "shop",
    at: "Sep 11 4:08p",
    text: "Elena, Priya from Cozy. Confirmed Sunday 6:00p with Marco. Both of you home?",
  },
{
    id: "M-1c",
    personId: "L-4821",
    channel: "call",
    from: "shop",
    at: "Sep 11 4:22p",
    text: "Call Out · Answered · 4 min",
    durationSec: 247,
    direction: "Out",
    result: "Answered",
  },
{
    id: "M-2",
    personId: "L-4821",
    channel: "sms",
    from: "customer",
    at: "Sep 11 4:19p",
    text: "Yes both of us. Dog will be in the backyard.",
  },
{
    id: "M-3",
    personId: "L-4821",
    channel: "sms",
    from: "shop",
    at: "Sep 12 8:14a",
    text: "Reminder set. Marco will text when he is 20 min out.",
  },
{
    id: "M-3e",
    personId: "L-4821",
    channel: "email",
    from: "shop",
    at: "Sep 12 8:20a",
    subject: "Sunday 6:00p confirmed",
    text: "Elena, confirming Marco Sunday at 6:00p for attic and air seal. Both of you home. Dog in the backyard is fine.",
  },
{
    id: "M-3er",
    personId: "L-4821",
    channel: "email",
    from: "customer",
    replyTo: "M-3e",
    at: "Sep 12 9:05a",
    subject: "Re: Sunday 6:00p confirmed",
    text: "Thanks. We'll both be home. Dog stays in the backyard.",
  },
{
    id: "M-3ef",
    personId: "L-4821",
    channel: "email",
    from: "shop",
    replyTo: "M-3e",
    at: "Sep 12 9:18a",
    subject: "Re: Sunday 6:00p confirmed",
    text: "Perfect. Marco will text when he is 20 minutes out.",
  },
{
    id: "M-4",
    personId: "L-4819",
    channel: "email",
    from: "shop",
    at: "Sep 12 9:44p",
    subject: "Proposal: HVAC + ducts",
    text: "Proposal for HVAC + ducts emailed. Cash and 12-month tiles on the file.",
  },
{
    id: "M-5",
    personId: "A-198",
    channel: "sms",
    from: "shop",
    at: "Sep 6 10:02a",
    text: "Install window Sep 18. Tasha will call the day before.",
  },
];

export const __rows2 = [
{
    id: "M-91r",
    personId: "L-4821",
    channel: "internal",
    from: "shop",
    at: "Sep 14 11:10a",
    text: "Board packet is on the portal. Need Elena's signature.",
    nest: { kind: "request", id: "R-12", title: "HOA architectural form" },
    actionId: "R-12",
    actionKind: "request",
  },
{
    id: "M-10",
    personId: "L-4774",
    channel: "sms",
    from: "customer",
    at: "Sep 15 11:02a",
    text: "Can we move Sunday? Kids have a game.",
  },
];
