import { getBrand } from "@/features/brand/store";
import type { MemberAgreement, MembershipFile } from "../types";
import { memberAgreement } from "../agreement";
import { rosterMemberships } from "@/lib/roster";

export function readyAgreement(file: MembershipFile): MemberAgreement {
  if (file.agreement?.status === "Signed") return file.agreement;
  return { status: "Ready", at: "", signer: "", body: memberAgreement(file, getBrand().name) };
}

export const membershipSeeds = [
  {
    id: "M-101",
    personId: "L-4761",
    name: "Ann Whitaker",
    address: "11820 E Shea Blvd",
    city: "Scottsdale, AZ",
    office: "Scottsdale",
    owner: "Dana Ortiz",
    planId: "comfort",
    planName: "Comfort",
    years: 3,
    pay: "prepaid",
    termPrice: 936,
    continueMonthly: 39,
    visitsPerYear: 2,
    status: "Active",
    startedFrom: "account",
    funding: "membership",
    start: "Mar 1, 2026",
    end: "Mar 1, 2029",
    nextBill: "",
  },
  {
    id: "M-102",
    personId: "L-4788",
    name: "Ben Cho",
    address: "9812 N 90th St",
    city: "Scottsdale, AZ",
    office: "Scottsdale",
    owner: "Dana Ortiz",
    planId: "comfort-plus",
    planName: "Comfort Plus",
    years: 1,
    pay: "billed",
    termPrice: 54,
    continueMonthly: 59,
    visitsPerYear: 2,
    status: "Active",
    startedFrom: "job",
    funding: "membership",
    start: "Sep 22, 2026",
    end: "Sep 22, 2027",
    nextBill: "Oct 22, 2026",
  },
  {
    id: "M-103",
    personId: "L-4819",
    name: "Todd Hale",
    address: "7721 E Via de Ventura",
    city: "Scottsdale, AZ",
    office: "Scottsdale",
    owner: "Dana Ortiz",
    planId: "comfort",
    planName: "Comfort",
    years: 5,
    pay: "prepaid",
    termPrice: 1500,
    continueMonthly: 39,
    visitsPerYear: 2,
    status: "Offered",
    startedFrom: "opportunity",
    funding: "loan",
    oppId: "O-1182",
    start: "Sep 26, 2026",
    end: "Sep 26, 2031",
    nextBill: "",
  },
  {
    id: "M-104",
    personId: "L-4726",
    name: "Paul Kerr",
    address: "6402 E Thunderbird Rd",
    city: "Scottsdale, AZ",
    office: "Scottsdale",
    owner: "Dana Ortiz",
    planId: "comfort",
    planName: "Comfort",
    years: 1,
    pay: "billed",
    termPrice: 32,
    continueMonthly: 39,
    visitsPerYear: 2,
    status: "Active",
    startedFrom: "account",
    funding: "membership",
    start: "Dec 1, 2025",
    end: "Dec 1, 2026",
    nextBill: "Oct 1, 2026",
  },
  ...rosterMemberships,
] as Array<Omit<MembershipFile, "included" | "repairDiscount">>;
