/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppAppointmentsRouteImport } from './routes/_app/appointments'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppConversationsRouteImport } from './routes/_app/conversations'
import { Route as AppCrewsRouteImport } from './routes/_app/crews'
import { Route as AppDispatchRouteImport } from './routes/_app/dispatch'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppScoreboardRouteImport } from './routes/_app/scoreboard'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts_.$accountId'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app/leads_.$leadId'
import { Route as AppOpportunitiesOppIdRouteImport } from './routes/_app/opportunities_.$oppId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects_.$projectId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewsRoute = AppCrewsRouteImport.update({
  id: '/crews',
  path: '/crews',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppScoreboardRoute = AppScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts_/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/leads_/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesOppIdRoute = AppOpportunitiesOppIdRouteImport.update({
  id: '/opportunities_/$oppId',
  path: '/opportunities/$oppId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/calendar': typeof AppCalendarRoute
  '/conversations': typeof AppConversationsRoute
  '/crews': typeof AppCrewsRoute
  '/dispatch': typeof AppDispatchRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/leads': typeof AppLeadsRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/scoreboard': typeof AppScoreboardRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/tickets': typeof AppTicketsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/opportunities/$oppId': typeof AppOpportunitiesOppIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof AppAccountsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/calendar': typeof AppCalendarRoute
  '/conversations': typeof AppConversationsRoute
  '/crews': typeof AppCrewsRoute
  '/dispatch': typeof AppDispatchRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/leads': typeof AppLeadsRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/scoreboard': typeof AppScoreboardRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/tickets': typeof AppTicketsRoute
  '/': typeof AppIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/opportunities/$oppId': typeof AppOpportunitiesOppIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/crews': typeof AppCrewsRoute
  '/_app/dispatch': typeof AppDispatchRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/scoreboard': typeof AppScoreboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts_/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/leads_/$leadId': typeof AppLeadsLeadIdRoute
  '/_app/opportunities_/$oppId': typeof AppOpportunitiesOppIdRoute
  '/_app/projects_/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/appointments'
    | '/calendar'
    | '/conversations'
    | '/crews'
    | '/dispatch'
    | '/leaderboard'
    | '/leads'
    | '/opportunities'
    | '/projects'
    | '/reports'
    | '/scoreboard'
    | '/settings'
    | '/team'
    | '/tickets'
    | '/accounts/$accountId'
    | '/leads/$leadId'
    | '/opportunities/$oppId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/appointments'
    | '/calendar'
    | '/conversations'
    | '/crews'
    | '/dispatch'
    | '/leaderboard'
    | '/leads'
    | '/opportunities'
    | '/projects'
    | '/reports'
    | '/scoreboard'
    | '/settings'
    | '/team'
    | '/tickets'
    | '/'
    | '/accounts/$accountId'
    | '/leads/$leadId'
    | '/opportunities/$oppId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/accounts'
    | '/_app/appointments'
    | '/_app/calendar'
    | '/_app/conversations'
    | '/_app/crews'
    | '/_app/dispatch'
    | '/_app/leaderboard'
    | '/_app/leads'
    | '/_app/opportunities'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/scoreboard'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/tickets'
    | '/_app/'
    | '/_app/accounts_/$accountId'
    | '/_app/leads_/$leadId'
    | '/_app/opportunities_/$oppId'
    | '/_app/projects_/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crews': {
      id: '/_app/crews'
      path: '/crews'
      fullPath: '/crews'
      preLoaderRoute: typeof AppCrewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispatch': {
      id: '/_app/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scoreboard': {
      id: '/_app/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof AppScoreboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts_/$accountId': {
      id: '/_app/accounts_/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads_/$leadId': {
      id: '/_app/leads_/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities_/$oppId': {
      id: '/_app/opportunities_/$oppId'
      path: '/opportunities/$oppId'
      fullPath: '/opportunities/$oppId'
      preLoaderRoute: typeof AppOpportunitiesOppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects_/$projectId': {
      id: '/_app/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppConversationsRoute: typeof AppConversationsRoute
  AppCrewsRoute: typeof AppCrewsRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScoreboardRoute: typeof AppScoreboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppOpportunitiesOppIdRoute: typeof AppOpportunitiesOppIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppConversationsRoute: AppConversationsRoute,
  AppCrewsRoute: AppCrewsRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReportsRoute: AppReportsRoute,
  AppScoreboardRoute: AppScoreboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppOpportunitiesOppIdRoute: AppOpportunitiesOppIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
