/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts.$accountId'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app/leads.$leadId'
import { Route as AppOpportunitiesOppIdRouteImport } from './routes/_app/opportunities.$oppId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects.$projectId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppOpportunitiesOppIdRoute = AppOpportunitiesOppIdRouteImport.update({
  id: '/$oppId',
  path: '/$oppId',
  getParentRoute: () => AppOpportunitiesRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tickets': typeof AppTicketsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/opportunities/$oppId': typeof AppOpportunitiesOppIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof AppAccountsRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tickets': typeof AppTicketsRoute
  '/': typeof AppIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/opportunities/$oppId': typeof AppOpportunitiesOppIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/_app/opportunities/$oppId': typeof AppOpportunitiesOppIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/calendar'
    | '/leaderboard'
    | '/leads'
    | '/opportunities'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tickets'
    | '/accounts/$accountId'
    | '/leads/$leadId'
    | '/opportunities/$oppId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/calendar'
    | '/leaderboard'
    | '/leads'
    | '/opportunities'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tickets'
    | '/'
    | '/accounts/$accountId'
    | '/leads/$leadId'
    | '/opportunities/$oppId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/accounts'
    | '/_app/calendar'
    | '/_app/leaderboard'
    | '/_app/leads'
    | '/_app/opportunities'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/tickets'
    | '/_app/'
    | '/_app/accounts/$accountId'
    | '/_app/leads/$leadId'
    | '/_app/opportunities/$oppId'
    | '/_app/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/opportunities/$oppId': {
      id: '/_app/opportunities/$oppId'
      path: '/$oppId'
      fullPath: '/opportunities/$oppId'
      preLoaderRoute: typeof AppOpportunitiesOppIdRouteImport
      parentRoute: typeof AppOpportunitiesRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppOpportunitiesRouteChildren {
  AppOpportunitiesOppIdRoute: typeof AppOpportunitiesOppIdRoute
}

const AppOpportunitiesRouteChildren: AppOpportunitiesRouteChildren = {
  AppOpportunitiesOppIdRoute: AppOpportunitiesOppIdRoute,
}

const AppOpportunitiesRouteWithChildren =
  AppOpportunitiesRoute._addFileChildren(AppOpportunitiesRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppOpportunitiesRoute: typeof AppOpportunitiesRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppOpportunitiesRoute: AppOpportunitiesRouteWithChildren,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
